import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Header } from '@/components/Header';
import { Posts } from '@/components/Posts';
import { Layout } from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });

// eslint-disable-next-line @typescript-eslint/space-before-function-paren
export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Curious Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={inter.style}>
        <Layout>
          <Header />
          <Posts />
        </Layout>
      </main>
    </>
  );
}
